version: "3.3"

services:
  main-service:
    image: fastapi-env
    build: .
    ports: 
      - "443:1337"
    environment:
      DOMAIN: "metarack.art"
    depends_on:
      - "git-puller"
    volumes:
      - metarack:/metarack
      - ./private:/private
    working_dir: /metarack/server 
    entrypoint: ["/bin/sh", "-c" , "sleep 10 && python /metarack/server/src/main_app.py"]

  redirect-service:
    image: fastapi-env
    build: .
    ports: 
      - "80:1337"
    depends_on:
      - "git-puller"
    volumes:
      - metarack:/metarack
    working_dir: /metarack/server 
    entrypoint: ["/bin/sh", "-c" , "sleep 10 && python /metarack/server/src/https_redirect.py"]

  git-puller:
    image: git-puller
    build: .
    environment:
      GIT_PULL_INTERVAL: "10"
    volumes:
      - metarack:/metarack
      - ./src/git_puller.py:/git_puller.py
      - ./private/github-token:/github-token
    working_dir: / 
    entrypoint: ["python", "git_puller.py"]

volumes:
  metarack: