version: "3.3"

services:
  main-service:
    image: fastapi-env
    build: .
    ports: 
      - "4443:1337"
    environment:
      DOMAIN: "metarack.art"
    volumes:
      - ./src:/src
      - ./private:/private
      - ./website:/website
    entrypoint: ["python","/src/main_app.py"]

  redirect-service:
    image: fastapi-env
    build: .
    ports: 
      - "8080:1337"
    volumes:
      - ./src:/src  
    entrypoint: ["python","/src/https_redirect.py"]